### ISSUE TITLE
Issue with downloading a file hosted on Google Drive

### ISSUE THREAD

**Issue by Zero3K** [lordmulder/INetGet#5]
When downloading a file hosted on Google Drive, a HTML file is downloaded instead of the actual file. An example of a Google Drive link is https://drive.google.com/uc?id=1FIQ2MLSn3rUsIU6m8QlNlsHPpYJenGgX&export=download.

**Comment by lordmulder** [comment]
Hello.

Well, that is simply what the Google servers responds for that particular URL :wink:

Looks no different, if you open _that_ exact URL in the browser:

![image](https://user-images.githubusercontent.com/470590/37681425-f35f7e5a-2c86-11e8-9b21-da4f8ca2d72e.png)

No surprise Google doesn't allow ["deeplinks"](https://en.wikipedia.org/wiki/Deep_linking) to content files. They want you to "see" the website.

**BTW:** The "real" download URL for the actual content looks like this:
```
https://doc-14-9k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/untnqe74fiu2grt8u1srsu8b1uouh9k3/1521576000000/08882150369740744055/*/1FIQ2MLSn3rUsIU6m8QlNlsHPpYJenGgX?e=download
```
...but of course that URL contains a **_temporary_** session ID's (ticket). So this _exact_ URL can **not** be used for download again. You will have to visit the web-site again, in order to get a "fresh" download link :expressionless:

Regards,
MuldeR

**Comment by Zero3K** [comment]
So, then how do I download the file using INetGet? I am able to download it with other download managers.

EDIT: Maybe it could extract the real download url and use that when downloading a drive.google.com link.

**Comment by lordmulder** [comment]
**INetGet** is just a simple download tool. You will have to supply it with the "real" download URL, i.e. the *direct* URL to the actual content to be download. How do you get the "real" download URL out of the Google web-site? That is way out of scope for this simple tool, really. And, of course, there is **no** proper solution for this anyway: Even if you'd write a program that parses Google's HTML code and extracts the "real" download URL – tomorrow Google will change their HTML code (slightly) and your program breaks again...

----

How do other download managers do it? I don't know. You'd have to ask the respective author. But I guess they write special code that "steals" the DL-link out of the Google Drive site. And they update that code every couple of days, i.e. every time Google changes their HTML code (slightly). Cat and mouse game :smirk:
