### ISSUE TITLE
Issue with using it with FlashGot

### ISSUE THREAD

**Issue by Zero3K** [lordmulder/INetGet#8]
I am using the command line arguments template that is as follows:

-refer=[REFERER] --agent=[UA] [URL] C:\Users\Bryan\Desktop\[FNAME]

When I do that, downloading a file results in INetGet opening and then immediately closing. Here's what's being sent to it according to FlashGot's Log:

C:\Windows\INetGet.exe --verbose --refer= https://www.speedguide.net/downloads.php --agent= Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.9) Gecko/20100101 Goanna/3.4 Firefox/52.9 PaleMoon/27.8.1 https://www.speedguide.net/files/TCPOptimizer.exe C:\Users\Bryan\Desktop\ TCPOptimizer.exe -- async

**Comment by lordmulder** [comment]
Hello.

I don't understand how "FlashGot" is related here, but if a command-line argument contains any white-spaces, or characters with a special meaning for the command-line interpreter (such as **`&`**, **`<`** or **`>`**), then you have to wrap it in quotations marks – otherwise each space-separated token is treated like a separate command-line option, which probably means that the program errors out with "invalid option".

The correct command-line would look like:
```
INetGet.exe --refer="https://www.speedguide.net/downloads.php" --agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.9) Gecko/20100101 Goanna/3.4 Firefox/52.9 PaleMoon/27.8.1" https://www.speedguide.net/files/TCPOptimizer.exe TCPOptimizer.exe
```

**_Works for me:_**
![image](https://user-images.githubusercontent.com/470590/37686974-0aba0184-2c9a-11e8-9c80-f1a812f5e865.png)


BTW: This is _**not**_ specific to INetGet, but applies to pretty much all CLI applications...

Regards,
MuldeR

**Comment by Zero3K** [comment]
Well, FlashGot is what I use to get Pale Moon to download using it. Unless you can find another way for it to download using it.

EDIT: It turns out that I was using improper syntax. I had to put the parameters in the brackets along with the URL, etc.
